# Nixpacks Configuration for Railway - Backend Only Deployment
[variables]
NODE_ENV = "production"

# For backend-only deployment
[phases.setup]
dependsOn = []
cmds = [
  "echo 'Preparing backend-only deployment'",
  "echo 'Working directory: $(pwd)'",
  "echo 'Listing files: $(ls -la)'"
]

[phases.install]
dependsOn = ["setup"]
# Install only production dependencies
cmds = [
  "npm ci --only=production --no-optional",
  "echo 'Dependencies installed successfully'"
]

[phases.build]
dependsOn = ["install"]
cmds = ["echo 'No build step required for backend'"]

# Start the server directly
[start]
cmd = "node server.js"